dist: trusty # Required due to Xenial not working with oraclejdk8
language: java

notifications:
  email: false

jdk:
  - oraclejdk8

branches:
  only:
    - master
    - develop

script:
  - ./gradlew check
  - ./gradlew sonarqube -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=lachlanmckee-github -Dsonar.login=$SONAR_TOKEN
  - ./gradlew integrationCodeCoverageReport
  - bash <(curl -s https://codecov.io/bash) -c -F integration
  - ./gradlew unitCodeCoverageReport
  - bash <(curl -s https://codecov.io/bash) -c -F unit_tests

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar
