language: java

notifications:
  email: false

jdk:
  - oraclejdk8

branches:
  only:
    - master
    - develop

script:
  - ./gradlew check
  - if [ $TRAVIS_PULL_REQUEST != 'false' ];
    then ./gradlew sonarqube -Dsonar.analysis.mode=preview -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=lachlanmckee-github -Dsonar.login=$SONAR_TOKEN -Dsonar.github.pullRequest=$TRAVIS_PULL_REQUEST -Dsonar.github.repository=LachlanMcKee/gsonpath -Dsonar.github.oauth=$GITHUB_TOKEN;
    else ./gradlew sonarqube -Dsonar.analysis.mode=publish -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=lachlanmckee-github -Dsonar.login=$SONAR_TOKEN;
    fi
  - ./gradlew coreIntegrationCodeCoverageReport
  - bash <(curl -s https://codecov.io/bash) -c -F core_integration
  - ./gradlew coreUnitCodeCoverageReport
  - bash <(curl -s https://codecov.io/bash) -c -F core_unit_tests
  - ./gradlew extensionsIntegrationCodeCoverageReport
  - bash <(curl -s https://codecov.io/bash) -c -F extensions_integration
  - ./gradlew extensionsUnitCodeCoverageReport
  - bash <(curl -s https://codecov.io/bash) -c -F extensions_unit_tests

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar
